import logging
import base64
import boto3
import json
import os
import sys
from botocore.exceptions import ClientError

class Config:
    SECRET_KEY = 'you-will-never-guess'
    DEBUG = True
    DB_USERNAME = 'root'
    DB_PASSWORD = 'password'
    DATABASE_NAME = 'db'
    DB_HOST = '172.17.0.2'
    
    MYSQL_ROOT_PASSWORD = 'password'
    MYSQL_USER = 'root'
    MYSQL_ALLOW_EMPTY_PASSWORD = True
    SQLALCHEMY_DATABASE_URI='mysql://root:password@172.17.0.2/db'

    #DB_URI = "mysql://%s:%s@%s/%s" % (DB_USERNAME, os.environ['MYSQL_ROOT_PASSWORD'], DB_HOST, os.environ['MYSQL_DATABASE'])
    #(DB_USERNAME, DB_PASSWORD, DB_HOST, DATABASE_NAME)
    #SQLALCHEMY_DATABASE_URI = DB_URI
    SQLALCHEMY_TRACK_MODIFICATIONS = True
